# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 172.101.2.40
  port: "22"
  internal_address: 172.101.2.40
  role:
  - controlplane
  - etcd
  hostname_override: rke-master-0
  user: kubernetes
  docker_socket: /var/run/docker.sock
  labels:
    node.rke.io/name: rke-master-0
    node.rke.io/hostname: k8s-master07
  taints: []

# List of worker
- address: 172.101.2.41
  port: "22"
  internal_address: 172.101.2.41
  role:
  - worker
  hostname_override: rke-worker-0
  user: kubernetes
  docker_socket: /var/run/docker.sock
  labels:
    node.rke.io/name: rke-worker-0
    node.rke.io/hostname: db-elk-01
  taints: []


services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args:
      oidc-issuer-url: https://accounts.google.com
      oidc-username-claim: email
      oidc-client-id: 309634483271-a25edveudt1ae11fg0e68pfb0iqpcmun.apps.googleusercontent.com
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.51.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.50.0.0/16
    service_cluster_ip_range: 10.51.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.51.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: calico
  options: {}
  node_selector: {}
authentication:
  strategy: x509
  sans:
    - k8s-lab.devopsnd95.cf
    - 103.126.159.10
  webhook: null
addons: ""
addons_include:
- ./sre-cluster-role-binding.yaml


#system_images:
  #etcd: rancher/coreos-etcd:v3.3.15-rancher1
  #alpine: rancher/rke-tools:v0.1.51
  #nginx_proxy: rancher/rke-tools:v0.1.51
  #cert_downloader: rancher/rke-tools:v0.1.51
  #kubernetes_services_sidecar: rancher/rke-tools:v0.1.51
  #kubedns: rancher/k8s-dns-kube-dns:1.15.0
  #dnsmasq: rancher/k8s-dns-dnsmasq-nanny:1.15.0
  #kubedns_sidecar: rancher/k8s-dns-sidecar:1.15.0
  #kubedns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  #coredns: rancher/coredns-coredns:1.6.2
  #coredns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  #kubernetes: rancher/hyperkube:v1.16.3-rancher1
  #flannel: rancher/coreos-flannel:v0.11.0-rancher1
  #flannel_cni: rancher/flannel-cni:v0.3.0-rancher5
  #calico_node: rancher/calico-node:v3.8.1
  #calico_cni: rancher/calico-cni:v3.8.1
  #calico_controllers: rancher/calico-kube-controllers:v3.8.1
  #calico_ctl: ""
  #calico_flexvol: rancher/calico-pod2daemon-flexvol:v3.8.1
  #canal_node: rancher/calico-node:v3.8.1
  #canal_cni: rancher/calico-cni:v3.8.1
  #canal_flannel: rancher/coreos-flannel:v0.11.0
  #canal_flexvol: rancher/calico-pod2daemon-flexvol:v3.8.1
  #weave_node: weaveworks/weave-kube:2.5.2
  #weave_cni: weaveworks/weave-npc:2.5.2
  #pod_infra_container: rancher/pause:3.1
  #ingress: rancher/nginx-ingress-controller:nginx-0.25.1-rancher1
  #ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
  #metrics_server: rancher/metrics-server:v0.3.4
  #windows_pod_infra_container: rancher/kubelet-pause:v0.1.3

ssh_key_path: kubernetes.pem
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: v1.16.3-rancher1-1
private_registries: []
ingress:
  provider: none
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []

cluster_name: "rke-db"
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
restore:
  restore: false
  snapshot_name: ""
dns: null
